### ISSUE TITLE
compute the reverse of an expression

### ISSUE THREAD

**Issue by yboujraf** [aantthony/javascript-cas#9]
Dear @osnr , @aantthony 

I am looking to compute the reverse on an expression.

**Use case :**

$ is the output value for example of a sensor and the manufacturer gives us the expr1 as formula to convert the $ to a display value for the user

But when the user wants to interact with the sensor, he needs to translate the display value to an expr2 to be sure the sensor could interpret the value.

**That's my example :**

The user write the expr1 and the library compute the reverse of the expr1 to expr2
expr1 = 1 + log($, 2) 
expr2 = 2^($ - 1) 

expr1 = sin($ / 7.43) where $ is of type INTEGER 
expr2 = int(7.43 * asin($)) 

expr1 = $ - log($ / (e^(-$) * $^sin(1 / $)), 10) 
expr2 = exercise left to the reader  

Thanks in advance if you could help us to find a solution of our issue.

Best Regards
Youssef

**Comment by aantthony** [comment]
As I understand it you want to solve an equation. This repository can't do that and isn't maintained anymore.

Try using WolframAlpha instead. To solve your first example: https://www.wolframalpha.com/input/?i=solve+y+%3D+1+%2B+log%282%2C+x%29
